name: pennywise
description: "A new Flutter project."
publish_to: "none"

version: 2.0.0+5

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  intl: ^0.20.2
  fl_chart: ^1.1.1
  table_calendar: ^3.1.0
  local_auth: ^3.0.1
  flutter_secure_storage: ^10.0.0
  font_awesome_flutter: ^10.7.0
  flutter_credit_card: ^4.1.0
  csv: ^7.1.0
  share_plus: ^12.0.1
  image_picker: ^1.0.7
  flutter_local_notifications: ^20.1.0
  cryptography: ^2.6.0
  file_picker: ^8.0.0
  flutter_launcher_icons: ^0.14.4
  url_launcher: ^6.3.2
  google_mobile_ads: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^6.4.1
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/aditya.jpg
    - assets/fonts/space_grotesk/SpaceGrotesk-Regular.ttf
    - assets/fonts/space_grotesk/SpaceGrotesk-Medium.ttf
    - assets/fonts/space_grotesk/SpaceGrotesk-Light.ttf
    - assets/fonts/space_grotesk/SpaceGrotesk-SemiBold.ttf
    - assets/fonts/space_grotesk/SpaceGrotesk-Bold.ttf
  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Light.ttf
          weight: 300
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Bold.ttf
          weight: 700
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#2563EB"
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_foreground_inset: 0
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#2563EB"
    theme_color: "#2563EB"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"
